server:
  servlet:
    context-path: /api/v1
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://101.132.123.23:3306/montra_db?serverTimezone=UTC
    username: root
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        dialect.storage_engine: innodb
    show-sql: true
  mail:
    count: 1
    default-encoding: UTF-8
    host: smtp.qq.com
    password: uaauirdkuwypeche
    properties:
      mail:
        smtp:
          ssl:
            enable: true
    username: 2427971846@qq.com
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  redis:
    host: 122.112.234.17
    port: 3302
    server:
      pattern: cluster
    cluster:
      nodes:
        - 101.132.123.23:6380
    #    password: 1234
    database: 1
    timeout: 10000
    lettuce:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0

